config/routes.rb
GoodReadsClone::Application.routes.draw do
  resources :users, :only => [:index, :create, :update, :show, :new, :destroy] do
    collection do
      get 'activate'
    end
    resources :follows, only: [:create, :destroy]
    post 'approve', :to => 'users#send_activation_email'
  end

  resource :session, :only => [:create, :destroy, :new] do
    post 'mail_request'
  end

  get 'request', :to => 'sessions#request_entry'

  resources :books, :only => [:index, :show, :create] do
    resource :like, :only => [:create, :destroy]
    post 'review', :to => 'posts#create_review'
  end

  resource :admin, :only => [:index] do
    get 'home', :to => 'admins#index'
    get 'requests', :to => 'admins#activation'
    get 'users'
    get 'clubs'
  end

  resources :clubs, :only => [:index, :create, :show, :destroy] do
    post 'filter', :to => 'clubs#filter_show'
    post 'add_book', :to => 'clubs#add_book'
    resources :posts, :only => [:create]
    resource :memberships, only: [:create, :destroy]
  end

  resources :comments, only: [:index, :show, :destroy]

  resources :posts, only: [:show, :destroy] do
    resources :comments, only: [:new, :create]
  end

  resources :notifications, only: [:index]

  root :to => "home#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :book_id, :club_id, :user_id, :body, :title

  validates :book, :user, :body, presence: true

  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  belongs_to(
    :book,
    class_name: "Book",
    foreign_key: :book_id,
    primary_key: :id
  )

  belongs_to(
    :club,
    class_name: "Club",
    foreign_key: :club_id,
    primary_key: :id
  )

  has_many(
    :comments,
    class_name: "Comment",
    foreign_key: :post_id,
    primary_key: :id,
    dependent: :destroy
  )

  def top_level_comments
    self.comments.where(parent_id: 0).find(:all, :order => "created_at DESC")
  end

  def self.review_for(current_user_id, book_id)
    Post.where("club_id = ? AND user_id = ? AND book_id = ?", 0, current_user_id, book_id)[0]
  end

  def self.book_reviews(book_id)
    Post.where("club_id = ? AND book_id = ? ", 0, book_id)
  end

  def self.user_reviews(user_id)
    Post.where("club_id = ? AND user_id = ? ", 0, user_id).includes(:book)
  end

  def self.user_posts(user_id)
    Post.where("club_id <> ? AND user_id = ? ", 0, user_id).includes(:book)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :require_current_user!
  before_filter :no_double_review!, only: [:create_review]


  def create
    post = current_user.posts.new(params[:post])
    post.club_id = params[:club_id]
    club = Club.find(params[:club_id])

    is_saved = post.save

    unless is_saved
      flash[:errors] = post.errors.full_messages
    end

    if request.xhr?
      if is_saved
        # Notify user.followers that user made post
        current_user.notify_followers_new_post(post)

        # Notify club.members that new post made
        club.notify_members_new_post(post)

        render partial: "posts/post", locals: {post: post}
      else
        render json: post.errors.full_messages, status: :unprocessable_entity
      end
    else
      # Notify user.followers that user made post
      current_user.notify_followers_new_post(post)
      # Notify club.members that new post made
      club.notify_members_new_post(post)

      redirect_to club_url(club)
    end
  end

  # Creates a REVIEW
  def create_review
    review = current_user.posts.new(params[:post])

    review.book_id = params[:book_id]

    is_saved = review.save

    unless is_saved
      flash[:errors] = review.errors.full_messages
    end

    # remove book from wish list if it was there
    like = Like.where(user_id: current_user.id, book_id: params[:book_id],  taste: 0)[0]
    like.destroy if like

    if request.xhr?
      if is_saved
        # Notify user.followers that user made review
        current_user.notify_followers_new_review(review)

        render partial: "posts/post", locals: {post: review, modifiable: true, is_review: true}
      else
        render json: review.errors.full_messages, status: :unprocessable_entity
      end
    else
      book = Book.find(params[:book_id])
      # Notify user.followers that user made review
      current_user.notify_followers_new_review(review)

      redirect_to book_url(book.isbn)
    end

  end

  def no_double_review!
    book = Book.find(params[:book_id])
    @review = Post.review_for(current_user.id, book.id)

    unless @review.nil?
      flash[:errors] = ["Can't double review"]
      redirect_to book_url(book.isbn)
    end
  end
  
  def destroy
    post = Post.find(params[:id])

    book = Book.find( post.book_id )
    post.destroy
    
    if request.xhr?
      render partial: "posts/form_review", locals: {book: book}
    else
      redirect_to book_url(book.isbn)
    end

  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form_post.html.erb
<form class="post-form" action="<%=  club_posts_url(club.id) %>" method="POST" data-remote="true">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  </input>

  <textarea name="post[body]"></textarea>


  	<select class="post-book" name="post[book_id]">
      <option>Book List</option>
  		<% books.each do |book| %>
  		<option value="<%= book.id %>"><%= book.title %></option>
  		<% end %>
  	</select>


<input type="submit" value="Post!"></input>
</form>

app/views/posts/_form_review.html.erb
<form class="review-form" action="<%= book_review_url(book.id) %>" method="POST" data-remote="true">
  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  </input>

  <textarea name="post[body]"></textarea>

<input type="submit" value="Post!"></input>
</form>

app/views/posts/_list_posts.html.erb
<% is_review ||= false %>
<% modifiable ||= false %>
<% a_review = a_review || "" %>
<% a_post = a_post || "" %>
<% book_page = book_page || "" %>
<% club_page = club_page || "" %>


	<% posts.each do |post| %>
    <%=render partial: "posts/post", locals: {post: post, is_review: is_review, modifiable: modifiable} %>
	<% end %>

app/views/posts/_post.html.erb
<ul class="post">
  <a name="post<%= post.id %>"></a>
  <% modifiable ||= false %>
  <% is_review ||= false%>

  <% if modifiable %>
  <div class="modify-post">
    <%= button_to "DELETE",   post_url(post), class: "delete", method: :delete, :remote => true, form_class: "post-delete-form" %>
    <!-- <a  href="#" class="edit">edit</a> -->
  </div>
  <% end %>

   <header class="post-header">
 		<li class="poster">
      <img src="<%= post.user.image %>"></img>
      <a href="<%= user_url(post.user_id) %>"><%= post.user.name %></a>
    </li>
   	<li class="post-date"><%= post.created_at.to_date.to_formatted_s(:rfc822)  %></li>
   </header>

   <div class="post-contents">
   	<li class="post-body"><%= post.body %></li>
   </div>

   <footer class="post-footer">
     <% unless is_review %>
   	<li class="book-title">
 			<a href="<%= book_url(post.book.isbn) %>">
 				<%= post.book.title %>
 			</a>
     </li>
     <% end %>
     
 		<% unless post.club_id == 0 %>
 		<li class="club-title">
 			<a href="<%= club_url(post.club) %>">
 				:<%= post.club.title %>
 			</a>
 		</li>
 		<% end %>
    <li class="comment-button"><a href="#">Comments (<%= post.top_level_comments.count %>)</a></li>
   </footer>

   <div class="post-comments hide-tag">
     <div class="comment-form">
        <% if current_user %>
          <%= render "comments/form_comment", post: post, parent_id: 0 %>
        <% end %>
     </div>
     <div class="new-comment"></div>
     <div class="comments-list"><% post.top_level_comments.each do |comment| %>
       <%= render "comments/comment", comment: comment %>
       <% end %>
     </div>
    </div>

</ul>